[package]
name = "reduce-target"
version = "0.2.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

[dependencies]
# walkdir = "2.3.1"
anyhow = "1.0.31"
gumdrop = "0.8.0"
indexmap = { version = "1.4.0", features = ["rayon"] }
jwalk = "0.5.1"
rayon = "1.3.1"
